<header class="sticky top-0 z-50 border-b border-zinc-200 bg-white/95 backdrop-blur">
 @php($siteSettings = app(\App\Settings\GeneralSettings::class))
 @if($siteSettings->show_announcement && filled($siteSettings->announcement_text))
  <div class="store-primary-bg px-4 py-2 text-center text-[11px] font-semibold tracking-[0.16em] text-white uppercase sm:text-xs">{{ $siteSettings->announcement_text }} <span class="hidden sm:inline">· @guest <a href="{{ route('login') }}" class="underline-offset-4 hover:underline">Sign in</a> or <a href="{{ route('register') }}" class="underline-offset-4 hover:underline">create an account</a> @endguest</span></div>
 @endif
 <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <div class="flex min-h-16 items-center justify-between gap-3 py-3">
   <a href="{{ route('home') }}" class="flex shrink-0 items-center focus:outline-none focus-visible:ring-2 focus-visible:ring-zinc-900 focus-visible:ring-offset-4" aria-label="{{ $siteSettings->site_name }} home">
    @if(filled($siteSettings->site_logo_path))
     <img src="{{ asset('storage/' . $siteSettings->site_logo_path) }}" alt="{{ $siteSettings->site_name }}" class="h-10 w-auto max-w-40 object-contain sm:h-11 sm:max-w-48">
    @else
     <span class="text-2xl font-black tracking-[-.08em] text-zinc-950 uppercase sm:text-3xl">{{ $siteSettings->site_name ?? 'FLORA' }}</span>
    @endif
   </a>
   <form action="{{ route('products.index') }}" method="GET" class="hidden min-w-0 max-w-xl flex-1 md:block"><label for="desktop-search" class="sr-only">Search flowers and gifts</label><div class="relative"><svg class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-zinc-400" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m21 21-4.35-4.35m1.35-5.15a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0Z"/></svg><input id="desktop-search" name="keyword" value="{{ is_string(request('keyword')) ? request('keyword') : '' }}" type="search" placeholder="Search flowers, bouquets and gifts" class="h-11 w-full rounded-full border border-zinc-300 bg-white pl-11 pr-24 text-sm text-zinc-900 placeholder:text-zinc-500 focus:border-zinc-900 focus:outline-none focus:ring-2 focus:ring-zinc-900/15"><button type="submit" class="absolute right-1.5 top-1.5 rounded-full bg-zinc-950 px-4 py-2 text-xs font-semibold text-white hover:bg-zinc-700">Search</button></div></form>
   <div class="flex shrink-0 items-center gap-1 sm:gap-2">
    <a href="{{ route('wishlist.index') }}" aria-label="Wishlist" class="grid h-11 w-11 place-items-center rounded-full text-zinc-700 hover:bg-zinc-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-zinc-900 focus-visible:ring-offset-2"><svg class="h-5 w-5" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M12 20.5 4.9 13.7A4.6 4.6 0 0 1 11.4 7L12 7.6l.6-.6a4.6 4.6 0 0 1 6.5 6.7L12 20.5Z"/></svg></a>
    <a href="{{ route('cart.index') }}" aria-label="Shopping cart" class="relative grid h-11 w-11 place-items-center rounded-full text-zinc-700 hover:bg-zinc-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-zinc-900 focus-visible:ring-offset-2"><svg class="h-5 w-5" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M3 4h2l1.2 10.2a2 2 0 0 0 2 1.8h8.9a2 2 0 0 0 1.9-1.5L21 7H6.2M9 20a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm10 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"/></svg><span class="absolute right-0 top-0 grid h-5 min-w-5 place-items-center rounded-full bg-zinc-950 px-1 text-[10px] font-bold text-white"><livewire:cart-count /></span></a>
    @auth <a href="{{ route('profile.show') }}" class="hidden h-11 items-center rounded-full px-3 text-sm font-semibold text-zinc-700 hover:bg-zinc-100 sm:flex">Account</a> @else <a href="{{ route('login') }}" class="hidden h-11 items-center rounded-full border border-zinc-300 px-4 text-sm font-semibold text-zinc-900 hover:border-zinc-900 sm:flex">Sign in</a> @endauth
    <button type="button" id="mobile-menu-button" aria-controls="mobile-menu" aria-expanded="false" class="grid h-11 w-11 place-items-center rounded-full text-zinc-700 hover:bg-zinc-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-zinc-900 focus-visible:ring-offset-2 md:hidden"><span class="sr-only">Open menu</span><svg class="h-6 w-6" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M4 7h16M4 12h16M4 17h16"/></svg></button>
   </div>
  </div>
  <div class="pb-3 md:hidden"><form action="{{ route('products.index') }}" method="GET" class="relative"><label for="mobile-search" class="sr-only">Search flowers and gifts</label><svg class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-zinc-400" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m21 21-4.35-4.35m1.35-5.15a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0Z"/></svg><input id="mobile-search" name="keyword" value="{{ is_string(request('keyword')) ? request('keyword') : '' }}" type="search" placeholder="Search flowers and gifts" class="h-11 w-full rounded-full border-zinc-300 bg-white pl-11 pr-4 text-sm focus:border-zinc-900 focus:ring-zinc-900"></form></div>
  <div id="mobile-menu" class="hidden border-t border-zinc-200 py-3 md:hidden"><div class="grid gap-1">@guest <a href="{{ route('login') }}" class="rounded-lg px-3 py-3 text-sm font-semibold text-zinc-800 hover:bg-zinc-100">Sign in</a><a href="{{ route('register') }}" class="rounded-lg px-3 py-3 text-sm font-semibold text-zinc-800 hover:bg-zinc-100">Create an account</a> @else <a href="{{ route('profile.show') }}" class="rounded-lg px-3 py-3 text-sm font-semibold text-zinc-800 hover:bg-zinc-100">My account</a><a href="{{ route('orders.index') }}" class="rounded-lg px-3 py-3 text-sm font-semibold text-zinc-800 hover:bg-zinc-100">My orders</a><form method="POST" action="{{ route('logout') }}">@csrf <button type="submit" class="w-full rounded-lg px-3 py-3 text-left text-sm font-semibold text-zinc-800 hover:bg-zinc-100">Sign out</button></form> @endguest</div></div>
 </div>
 <nav class="border-t border-zinc-100 bg-zinc-50" aria-label="Product categories"><div class="mx-auto max-w-7xl overflow-x-auto px-4 sm:px-6 lg:px-8"><x-filament-menu-builder::menu slug="main" view="components.menus.home-category-menu" /></div></nav>
</header>
<script>document.addEventListener('DOMContentLoaded',()=>{const t=document.getElementById('mobile-menu-button'),m=document.getElementById('mobile-menu');if(!t||!m)return;t.addEventListener('click',()=>{const o=!m.classList.contains('hidden');m.classList.toggle('hidden',o);t.setAttribute('aria-expanded',String(!o));t.querySelector('.sr-only').textContent=o?'Open menu':'Close menu';});});</script>
